import React from 'react'
import Head from 'next/head'
import DashboardLayout from '@/layout/DashboardLayout'
import styles from '@/styles/Objectives.module.css'
import { Row, Col } from 'react-bootstrap'
import CustomButton from '@/components/CustomButton/customButton'
import { MdAddTask } from 'react-icons/md'
import ObjectiveList from '@/components/ObjectiveList/objectiveList'

const Objectives = () => {
      return (
            <>
                  <Head>
                        <title>Create Next App</title>
                        <meta name="description" content="Generated by create next app" />
                        <meta name="viewport" content="width=device-width, initial-scale=1" />
                        <link rel="icon" href="/favicon.ico" />
                  </Head>
                  <main>
                        <DashboardLayout screen={"objectives"}>
                              <div className={'d-flex align-items-center justify-content-between'} >
                                    <div className={'d-flex link align-items-center'} >
                                          <MdAddTask />
                                          <p className={'ps-2'} >Add Objective</p>
                                    </div>
                                    <div>
                                          <p>sort By</p>
                                    </div>
                              </div>
                              <ObjectiveList />
                        </DashboardLayout>
                  </main>
            </>
      )
}

export default Objectives
