import React, {useState} from 'react'
import Head from 'next/head'
import DashboardLayout from '@/layout/DashboardLayout'
import styles from '@/styles/Objectives.module.css'
import { Row, Col } from 'react-bootstrap'
import CustomButton from '@/components/CustomButton/customButton'
import { MdAddTask } from 'react-icons/md'
import ObjectiveList from '@/components/ObjectiveList/objectiveList'
import CreateObjective from '@/components/Modals/CeateObjective'
import { getAllMyObjectives } from '@/services/api'
import { useQuery } from 'react-query'
import {toast} from 'react-toastify'
import Loader from '@/components/Loader/Loader'
import NotFound from '@/components/NotFound/NotFound'

const MyObjectives = () => {
      const [show, setShow] = useState(false);

      const { isLoading, isError, data=[], error, refetch } = useQuery('getAllMyObjective', () => getAllMyObjectives())

      if(data){
            console.log(data)
      }

      return (
            <>
                  <Head>
                        <title>Create Next App</title>
                        <meta name="description" content="Generated by create next app" />
                        <meta name="viewport" content="width=device-width, initial-scale=1" />
                        <link rel="icon" href="/favicon.ico" />
                  </Head>
                  <main>
                        <DashboardLayout screen={"my objectives"}>
                              <div className={'d-flex align-items-center justify-content-between'} >
                                    <CreateObjective show={show} setShow={(v)=>{setShow(v); refetch()}} screen={"myObjectives"} />
                                    <div className={'d-flex link align-items-center'} >
                                          {/* <MdAddTask /> */}
                                          <CustomButton text={"Add Objective"}  className={'px-4'} nofilled onClick={()=>setShow(true)} />
                                          {/* <p ></p> */}
                                    </div>
                                    <div>
                                          <p>sort By</p>
                                    </div>
                              </div>
                              {
                                    isLoading && 
                                    <Loader />
                              }
                              {
                                    data.length == 0 && !isLoading &&
                                    <div style={{position : "relative", minHeight : '65vh'}} >
                                          <NotFound 
                                          title={"No Objectives found"} 
                                          desc={"Click the button below to add your first objective"} 
                                          btnText={"Add Objective"}
                                          onClick={()=>setShow(true)}
                                          />
                                    </div>
                              }
                              <ObjectiveList screen={"myObjectives"} data={data || []} cb={()=> refetch()} />
                        </DashboardLayout>
                  </main>
            </>
      )
}

export default MyObjectives
