import Head from 'next/head'
import styles from '@/styles/Onboarding.module.css'
import { Row, Col } from 'react-bootstrap'
import Custom_input from '@/components/CustomInput/custom_input'
import { useState } from 'react'
import CustomButton from '@/components/CustomButton/customButton'
import Custom_dropdown from '@/components/CustomInput/custom_dropdown'
import { useRouter } from 'next/router'
import { useQuery } from 'react-query'
import { userInfo } from '@/services/api'

const options = [
	{
		label : "Male",
		value : "male"
	},
	{
		label : "Female",
		value : "female"
	}
]

export default function ProfileInfo() {

	const [fname, setFname] = useState('');
	const [fnameError, setFnameError] = useState('');
	const [lname, setLname] = useState('');
	const [lnameError, setLnameError] = useState('');
	const [dob, setDob] = useState('');
	const [dobError, setDobError] = useState('');
	const [gender, setGender] = useState('');
	const [genderError, setGenderError] = useState('');
          const router = useRouter();
	const { email } = router.query //type can be verifyEmail or forgotPassword

	const { isLoading, isError, data, error, refetch } = useQuery('userInfo', () => userInfo({
		email : email.toLowerCase(), 
		firstName : fname,
		lastName : lname,
		gender : gender.value,
		dateOfBirth : dob
	}),{
		enabled : false,
		cacheTime : 0
	})
	if(data){
		router.push('/login')
	}
	if(isError){
		console.log(error)
	}

	function submitForm(){
		let flag = 0;
		if(fname == '') {flag=1; setFnameError("First name can't be blank");}
		if(lname == '') {flag=1; setLnameError("Last name can't be blank");}
		if(dob == '') {flag=1; setDobError("Date of birth can't be blank");}
		if(gender == '') {flag=1; setGenderError("Please select your gender");}

		if(flag == 0){
			refetch();
		}
	}

	return (
		<>
			<Head>
				<title>Create Next App</title>
				<meta name="description" content="Generated by create next app" />
				<meta name="viewport" content="width=device-width, initial-scale=1" />
				<link rel="icon" href="/favicon.ico" />
			</Head>
			<main>
				<Row>
					<Col xl={6} lg={8} sm={12}  className={styles.leftCol + " allcenter"} >
						<div className={styles.leftWrapper}>
							<h1>Account Details</h1>
							<p>We need some information about you</p>
							<Custom_input id="firstname" required type={'text'} placeholder={'John'} value={fname} setValue={setFname} className={'mt-5'} title={'First Name'} error={fnameError} setError={setFnameError}  />
							<Custom_input id="lastname" required type={'text'} placeholder={'Doe'} value={lname} setValue={setLname} className={'my-3'} title={'Last Name'} error={lnameError} setError={setLnameError}  />
							<Custom_input id="dob" required type={'date'} placeholder={''} value={dob} setValue={setDob} className={'my-3'} title={'Date of Birth'} error={dobError} setError={setDobError}  />
							<Custom_dropdown id={gender} options={options} className={'my-3 mb-5'} title={'Gender'} required placeholder={'Select gender'} value={gender} setValue={setGender} error={genderError} setError={setGenderError} />
							{
								isError && <p className="text-center my-3 text-danger" >{error?.response?.data?.message}</p>
							}
							<p className={styles.codeDigit} >Your data will be safe and secure</p>
                                                                      <CustomButton text={"Submit"} onClick={()=>submitForm()} className={"my-4"} loading={isLoading} />
						</div>
					</Col>
					<Col xl={6} lg={4} sm={12} className={styles.imageSection + " d-none d-lg-block"}>
						<img src="https://mir-s3-cdn-cf.behance.net/projects/max_808_webp/3c8fa3161199455.Y3JvcCwxOTIwLDE1MDEsMCwxOQ.png" alt="Dashboard image" />
					</Col>
				</Row>
			</main>
		</>
	)
}
