import React, {useState} from 'react'
import Head from 'next/head'
import { Row, Col } from 'react-bootstrap'
import DashboardLayout from '@/layout/DashboardLayout'
import CustomButton from '@/components/CustomButton/customButton'
import styles from './team.module.css'
import { MdAddTask } from 'react-icons/md'
import ObjectiveList from '@/components/ObjectiveList/objectiveList'
import CreateObjective from '@/components/Modals/CeateObjective'
import CreateTeam from '@/components/Modals/CreateTeam'

const Team = () => {
  const [show, setShow] = useState(false);
  return (
        <>
              <Head>
                    <title>Create Next App</title>
                    <meta name="description" content="Generated by create next app" />
                    <meta name="viewport" content="width=device-width, initial-scale=1" />
                    <link rel="icon" href="/favicon.ico" />
              </Head>
              <main>
                    <DashboardLayout screen={"teams"}>
                          <div className={'d-flex align-items-center justify-content-between'} >
                                <CreateTeam show={show} setShow={(v)=>setShow(v)} screen={"teams"} />
                                <div className={'d-flex link align-items-center'} >
                                      {/* <MdAddTask /> */}
                                      <CustomButton text={"Add Team"}  className={'px-4'} nofilled onClick={()=>setShow(true)} />
                                      {/* <p ></p> */}
                                </div>
                                <div>
                                      <p>sort By</p>
                                </div>
                          </div>
                    </DashboardLayout>
              </main>
        </>
  )
}

export default Team
