import Head from 'next/head'
import styles from '@/styles/Onboarding.module.css'
import { Row, Col, Form } from 'react-bootstrap'
import Custom_input from '@/components/CustomInput/custom_input'
import { useState } from 'react'
import CustomButton from '@/components/CustomButton/customButton'
import Link from 'next/link'
import { useRouter } from 'next/router'

export default function ConfirmOtp() {

	const [otp, setotp] = useState('');
	const [otpError, setotpError] = useState('');
	const router = useRouter();
	const { email } = router.query


	function submitForm(){
		let flag = 0;
		if(otp == '') {flag=1; setotpError("otp can't be blank");}

		if(flag == 0){
			router.push('/change-password');
		}
	}

	return (
		<>
			<Head>
				<title>Create Next App</title>
				<meta name="description" content="Generated by create next app" />
				<meta name="viewport" content="width=device-width, initial-scale=1" />
				<link rel="icon" href="/favicon.ico" />
			</Head>
			<main>
				<Row>
					<Col xl={6} lg={8} sm={12}  className={styles.leftCol + " allcenter"} >
						<div className={styles.leftWrapper}>
							<h1>Confirm OTP</h1>
							<p>a four digit verification code has been sent on <Link href="#" className="link" >{email}</Link></p>
							<Custom_input id="otp" required type={'text'} placeholder={'OTP'} value={otp} setValue={setotp} className={'my-5'} title={'Enter OTP'} error={otpError} setError={setotpError}  />
							<p className={styles.codeDigit} >OTP not recieved? <span className="accentText" >Resend OTP</span></p>
                                                                      <CustomButton text={"Confirm"} onClick={()=>submitForm()} className={"my-4"} />
						</div>
					</Col>
					<Col xl={6} lg={4} sm={12} className={styles.imageSection + " d-none d-lg-block"}>
						<img src="https://mir-s3-cdn-cf.behance.net/projects/max_808_webp/3c8fa3161199455.Y3JvcCwxOTIwLDE1MDEsMCwxOQ.png" alt="Dashboard image" />
					</Col>
				</Row>
			</main>
		</>
	)
}
