import Head from 'next/head'
import DashboardLayout from '@/layout/DashboardLayout'
import ObjectiveCard from '@/components/ObjectiveCard/objectiveCard'
import {Row, Col} from 'react-bootstrap'
import styles from '@/styles/home.module.css'

export default function Home() {
	return (
		<>
			<Head>
				<title>Create Next App</title>
				<meta name="description" content="Generated by create next app" />
				<meta name="viewport" content="width=device-width, initial-scale=1" />
				<link rel="icon" href="/favicon.ico" />
			</Head>
			<main>
				<DashboardLayout>
					<Row>
						<Col lg={7} >
							<p className={styles.heading} >Recent Objectives</p>
							<Row className="mt-3" >
								<Col lg={6} >
									<ObjectiveCard />
								</Col>
								<Col lg={6} >
									<ObjectiveCard />
								</Col>
							</Row>
						</Col>
						<Col lg={5} ></Col>
					</Row>
				</DashboardLayout>
			</main>
		</>
	)
}
