import Head from 'next/head'
import DashboardLayout from '@/layout/DashboardLayout'
import ObjectiveCard from '@/components/ObjectiveCard/objectiveCard'
import {Row, Col} from 'react-bootstrap'
import styles from '@/styles/home.module.css'
import OverallProgress from '@/components/OverallProgress/overallProgress'
import DetailedProgress from '@/components/DetailedProgress/detailedProgress'
import Teams from '@/components/Teams/Teams'
import VisualProgress from '@/components/VisualProgress/visualProgress'

export default function Home() {
	return (
		<>
			<Head>
				<title>Create Next App</title>
				<meta name="description" content="Generated by create next app" />
				<meta name="viewport" content="width=device-width, initial-scale=1" />
				<link rel="icon" href="/favicon.ico" />
			</Head>
			<main>
				<DashboardLayout screen={"home"}>
					<OverallProgress />
					<Row>
						<Col lg={8} xs={12} >
							<VisualProgress />
						</Col>
						<Col lg={4} xs={12} >
						<Teams />
						</Col>
					</Row>
					<DetailedProgress />
					{/* <Row>
						<Col lg={8} xs={12} >
							<DetailedProgress />
						</Col>
						<Col lg={4}  xs={12} >
							<Teams />
						</Col>
					</Row> */}
				</DashboardLayout>
			</main>
		</>
	)
}
