import Head from 'next/head'
import styles from '@/styles/Onboarding.module.css'
import { Row, Col, Form } from 'react-bootstrap'
import Custom_input from '@/components/CustomInput/custom_input'
import { useState } from 'react'
import CustomButton from '@/components/CustomButton/customButton'
import { useRouter } from 'next/router'
import {toast} from 'react-toastify'
import { useQuery } from 'react-query'
import { changePassword } from '@/services/api'

export default function ConfirmPassword() {

	const [password, setpassword] = useState('');
          const [conpassword, setconpassword] = useState('');
	const [passwordError, setpasswordError] = useState('');
          const [conpasswordError, setconpasswordError] = useState('');
          const router = useRouter();
	const { email, otp } = router.query;

	const { isLoading, isError, data, error, refetch } = useQuery('changePassword', () => changePassword({email, otp, password}),{
		enabled : false,
		cacheTime : 0
	})

	if(data){
		toast.success("Password changed successfully");
		router.push('/login');
	}

	if(isError){
		console.log(error)
	}

	function submitForm(){
		let flag = 0;
		if(password == '') {flag=1; setpasswordError("Password can't be blank");}
                    else if(password.length < 6) {flag=1; setpasswordError("Password cannot be less than 6 characters");}
                    if(conpassword != password) {flag=1; setconpasswordError("Password does not match");}
		if(flag == 0){
                              refetch();
		}
	}

	return (
		<>
			<Head>
				<title>Create Next App</title>
				<meta name="description" content="Generated by create next app" />
				<meta name="viewport" content="width=device-width, initial-scale=1" />
				<link rel="icon" href="/favicon.ico" />
			</Head>
			<main>
				<Row>
					<Col xl={6} lg={8} sm={12}  className={styles.leftCol + " allcenter"} >
						<div className={styles.leftWrapper}>
							<h1>Change Password</h1>
							<p>Set up a strong password for being secured</p>
							<Custom_input id="password" required type={'password'} placeholder={'Password'} value={password} setValue={setpassword} className={'mt-5'} title={'Enter Password'} error={passwordError} setError={setpasswordError}  />
							<Custom_input id="conpassword" required type={'password'} placeholder={'Confirm Password'} value={conpassword} setValue={setconpassword} className={'mt-3 mb-5'} title={'Confirm Password'} error={conpasswordError} setError={setconpasswordError}  />
							{
								isError && <p className="text-center mb-2 text-danger" >{error?.response?.data?.message}</p>
							}
                                                                      <CustomButton text={"Confirm"} onClick={()=>submitForm()} className={"my-4"} loading={isLoading} />
						</div>
					</Col>
					<Col xl={6} lg={4} sm={12} className={styles.imageSection + " d-none d-lg-block"}>
						<img src="https://mir-s3-cdn-cf.behance.net/projects/max_808_webp/3c8fa3161199455.Y3JvcCwxOTIwLDE1MDEsMCwxOQ.png" alt="Dashboard image" />
					</Col>
				</Row>
			</main>
		</>
	)
}
