import React, { useState } from 'react'
import DashboardLayout from '@/layout/DashboardLayout'
import CustomButton from '@/components/CustomButton/customButton'
import Head from 'next/head'
import styled from '@emotion/styled'
import NotFound from '@/components/NotFound/NotFound'
import CreateOrganization from '@/components/Modals/CreateOrganization'
import OrganizationCard from '@/components/OrganizationCard/OrganizationCard'

const Organization = () => {

      const [show, setShow] = useState(false);

      return (
            <>
                  <Head>
                        <title>Create Next App</title>
                        <meta name="description" content="Generated by create next app" />
                        <meta name="viewport" content="width=device-width, initial-scale=1" />
                        <link rel="icon" href="/favicon.ico" />
                  </Head>
                  <main>
                        <DashboardLayout screen={"organization"} >
                              <>
                                    <CreateOrganization show={show} setShow={(e)=>setShow(e)} />
                                    <div className={'d-flex align-items-center justify-content-between'} >
                                          <div className={'d-flex link align-items-center'} >
                                                <CustomButton text={"Create Organization"} className={'px-4'} nofilled onClick={() => setShow(true)} />
                                          </div>
                                          <div>
                                                <p>sort By</p>
                                          </div>
                                    </div>
                                    <OrgWrapper>
                                          {/* <NotFound
                                                title={"No Active Organization Found"}
                                                desc={"You are not part of any organazation to access this featue. Ask your manager to invite you or create your own organization."}
                                                btnText={"Create Organization"}
                                                onClick={() => setShow(true)}
                                          /> */}
                                          <div className='mt-2' >
                                                <OrganizationCard />
                                                <OrganizationCard />
                                          </div>
                                    </OrgWrapper>
                              </>
                        </DashboardLayout>
                  </main>
            </>
      )
}

export default Organization

const OrgWrapper = styled.div`
      position : relative;
      min-height : 60vh;
`
